/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["paste"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/share-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shareLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["item"];
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["insertTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}/turns/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editTurn"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}/units/{unitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["unit"];
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["readAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/presentations/{presentationId}/aids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordAid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/presentations/{presentationId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/presentations/{presentationId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current"];
        put?: never;
        post: operations["decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/{practiceId}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/first-study": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["firstStudy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/first-study/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startFirstStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/first-study/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/learning-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["options_1"];
        put: operations["choose_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/memory-gauge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gauge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/memory-strength": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["options"];
        put: operations["choose"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AidRequest: {
            /** @enum {string} */
            type: "INTERPRETATION" | "HINT" | "EXPLANATION";
        };
        AidView: {
            /** Format: int64 */
            aidId: number;
            /** Format: date-time */
            exposedAt: string;
            /** @enum {string} */
            type: "INTERPRETATION" | "HINT" | "EXPLANATION";
        };
        AttemptView: {
            /** Format: int64 */
            attemptId: number;
            correct: boolean | null;
            evaluated: boolean;
            /** @enum {string|null} */
            holdReason: "LOW_CONFIDENCE" | "UNABLE_TO_JUDGE" | "MISREAD" | "GUESS_UNCONFIRMED" | null;
            judgment: components["schemas"]["JudgmentView"];
            /** @enum {string} */
            kind: "FIRST_UNASSISTED" | "ASSISTED_RETRY" | "DELAYED_RECHECK";
            /** @enum {string|null} */
            rating: "AGAIN" | "HARD" | "GOOD" | "EASY" | null;
            /** Format: int64 */
            responseTimeMs: number;
        };
        Composition: {
            goals: components["schemas"]["GoalSummary"][];
            /** Format: int32 */
            maxQuestions: number;
            questions: components["schemas"]["PlannedQuestion"][];
            unplannedItemIds: number[];
        };
        ConfusionPointResponse: {
            /** Format: int32 */
            turn: number;
            userBelief: string;
        };
        ConversationDetailResponse: {
            /** @enum {string} */
            fidelity: "verbatim" | "model_transcribed";
            id: string;
            /** @enum {string} */
            inputPath: "connector" | "share_link" | "paste";
            /** Format: date-time */
            receivedAt: string;
            reviewUnits: components["schemas"]["ReviewUnitResponse"][];
            topicHint: string | null;
            userTurns: components["schemas"]["UserTurnResponse"][];
            warnings: string[];
        };
        ConversationSummaryResponse: {
            /** @enum {string} */
            fidelity: "verbatim" | "model_transcribed";
            id: string;
            /** @enum {string} */
            inputPath: "connector" | "share_link" | "paste";
            /** Format: date-time */
            receivedAt: string;
            /** Format: int32 */
            reviewUnitCount: number;
            topicHint: string | null;
            /** Format: int32 */
            userTurnCount: number;
            /** Format: int32 */
            warningCount: number;
        };
        DailyItemView: {
            /** Format: int64 */
            estimatedSeconds: number;
            held: boolean;
            /** @enum {string} */
            kind: "FACT" | "WARNING" | "PRACTICE" | "CONFUSION";
            /** Format: int64 */
            learningSessionId: number;
            /** Format: int64 */
            memoryItemId: number;
            /** @enum {string} */
            questionType: "MULTIPLE_CHOICE" | "SHORT_ANSWER" | "ESSAY" | "ERROR_FINDING" | "CASE_JUDGMENT" | "CASE_APPLICATION";
            relearnToday: boolean;
            /** Format: double */
            retrievability: number | null;
            /** @enum {string} */
            source: "REVIEW" | "NEW";
        };
        DailyView: {
            /** Format: int32 */
            carriedOver: number;
            completed: boolean;
            /** Format: date */
            date: string;
            /** Format: int64 */
            estimatedSeconds: number;
            items: components["schemas"]["DailyItemView"][];
            /** Format: int32 */
            newCount: number;
            /** Format: int64 */
            practiceId: number | null;
            /** Format: int32 */
            reviewCount: number;
            started: boolean;
            /** Format: int32 */
            total: number;
            unavailable: number[];
        };
        ExclusionRequest: {
            excluded: boolean;
        };
        FeedbackView: {
            /** @enum {string|null} */
            action: "ADVANCE" | "RETRY" | "GIVE_HINT" | "EXPLAIN_CONCEPT" | "GENERATE_VARIANT" | "RELEARN_TODAY" | "REQUEST_CONFIRMATION" | null;
            /** @enum {string|null} */
            decidedBy: "RULE" | "JEV" | "FALLBACK" | null;
            evidenceTurns: number[];
            explanation: string | null;
            hint: string | null;
            /** @enum {string|null} */
            path: "INDEPENDENT" | "AFTER_HINT" | "AFTER_EXPLANATION" | "REPEATED_WRONG" | null;
            prerequisite: components["schemas"]["Prerequisite"];
            /** Format: int64 */
            presentationId: number;
            reason: string | null;
            recheckQueued: boolean;
        };
        FirstStudy: {
            failed: boolean;
            failureReason: string | null;
            generating: boolean;
            held: components["schemas"]["HeldSlot"][];
            /** Format: int32 */
            planned: number;
            questions: components["schemas"]["QuestionView"][];
            /** @enum {string} */
            sessionStatus: "RECEIVED" | "REVIEWING" | "AWAITING_CONFIRMATION" | "CONFIRMED" | "QUESTIONS_READY" | "IN_PROGRESS";
        };
        GoalSummary: {
            /** Format: int32 */
            candidates: number;
            /** @enum {string} */
            goal: "KEY_RECALL" | "PRINCIPLE" | "DISTINGUISH" | "CONDITION" | "APPLY_CASE" | "CORRECT_MISCONCEPTION" | "EXPLAIN_OWN_WORDS";
            /** Format: int32 */
            planned: number;
            reason: string | null;
        };
        GoalView: {
            description: string;
            /** @enum {string} */
            goal: "KEY_RECALL" | "PRINCIPLE" | "DISTINGUISH" | "CONDITION" | "APPLY_CASE" | "CORRECT_MISCONCEPTION" | "EXPLAIN_OWN_WORDS";
            label: string;
            /** Format: int32 */
            number: number;
        };
        GoalsRequest: {
            goals: ("KEY_RECALL" | "PRINCIPLE" | "DISTINGUISH" | "CONDITION" | "APPLY_CASE" | "CORRECT_MISCONCEPTION" | "EXPLAIN_OWN_WORDS")[];
            /** @enum {string} */
            strength: "LIGHT" | "UNDERSTAND" | "APPLY" | "MASTER";
        };
        HeldSlot: {
            /** Format: int64 */
            memoryItemId: number;
            /** Format: int32 */
            position: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "SHORT_ANSWER" | "ESSAY" | "ERROR_FINDING" | "CASE_JUDGMENT" | "CASE_APPLICATION";
        };
        IntakeResponse: {
            conversationId: string;
            inputPath: string;
            /** Format: int32 */
            reviewUnitCount: number;
            /** Format: int32 */
            userTurnCount: number;
            warnings: string[];
        };
        Item: {
            content: string;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            kind: "FACT" | "WARNING" | "PRACTICE" | "CONFUSION";
            sourceTurns: number[];
            /** @enum {string} */
            status: "NEW" | "ACTIVE" | "EXCLUDED";
        };
        ItemGauge: {
            checked: boolean;
            /** Format: int64 */
            memoryItemId: number;
            /** Format: int32 */
            percent: number | null;
            /** Format: double */
            retrievability: number | null;
        };
        ItemView: {
            content: string;
            gauge: components["schemas"]["ItemGauge"];
            /** @enum {string} */
            kind: "FACT" | "WARNING" | "PRACTICE" | "CONFUSION";
            /** Format: int64 */
            memoryItemId: number;
        };
        JudgmentView: {
            judged: boolean;
            misconceptionRecurred: boolean;
            /** @enum {string|null} */
            reason: "CONTRADICTION" | "OMISSION" | "MISREAD" | null;
            /** @enum {string|null} */
            verdict: "MET" | "NOT_MET" | "UNABLE_TO_JUDGE" | null;
        };
        KeyPointResponse: {
            /** @enum {string} */
            kind: "fact" | "warning" | "practice";
            point: string;
            turns: number[];
        };
        LearningSessionDetail: {
            /** Format: date-time */
            confirmedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            fidelity: string;
            /** Format: int64 */
            id: number;
            inputPath: string;
            /** @enum {string} */
            status: "RECEIVED" | "REVIEWING" | "AWAITING_CONFIRMATION" | "CONFIRMED" | "QUESTIONS_READY" | "IN_PROGRESS";
            topicHint: string | null;
            turns: components["schemas"]["Turn"][];
            units: components["schemas"]["Unit"][];
            warnings: string[];
        };
        LearningSessionSummary: {
            /** Format: date-time */
            createdAt: string;
            fidelity: string;
            /** Format: int64 */
            id: number;
            inputPath: string;
            /** Format: int32 */
            itemCount: number;
            /** @enum {string} */
            status: "RECEIVED" | "REVIEWING" | "AWAITING_CONFIRMATION" | "CONFIRMED" | "QUESTIONS_READY" | "IN_PROGRESS";
            topicHint: string | null;
            /** Format: int32 */
            unitCount: number;
        };
        NewTurnRequest: {
            /** Format: int32 */
            afterIndex: number;
            /** @enum {string|null} */
            aiVerdict: "confirmed" | "partial" | "corrected" | "not_applicable" | null;
            correction: string | null;
            /** @enum {string} */
            intent: "info_request" | "rephrase_request" | "understanding_check" | "restatement" | "challenge" | "meta";
            sourceOf: number[] | null;
            text: string;
        };
        Next: {
            done: boolean;
            presentation: components["schemas"]["PresentationView"];
        };
        NotificationView: {
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            id: number;
            read: boolean;
            /** Format: int64 */
            targetId: number;
            title: string;
            type: string;
        };
        NotificationsView: {
            items: components["schemas"]["NotificationView"][];
            /** Format: int64 */
            unreadCount: number;
        };
        Option: {
            /** Format: double */
            dailyMinutes: number;
            /** Format: double */
            desiredRetention: number;
            label: string;
            /** Format: int32 */
            maxQuestionLevel: number;
            /** Format: int32 */
            reviewsInPeriod: number;
            /** @enum {string} */
            strength: "LIGHT" | "UNDERSTAND" | "APPLY" | "MASTER";
        };
        Options: {
            /** @enum {string|null} */
            current: "LIGHT" | "UNDERSTAND" | "APPLY" | "MASTER" | null;
            /** Format: int32 */
            itemCount: number;
            options: components["schemas"]["Option"][];
            /** Format: int32 */
            simulationDays: number;
        };
        OptionsView: {
            available: components["schemas"]["GoalView"][];
            /** Format: int32 */
            maxSelected: number;
            plan: components["schemas"]["Composition"];
            saved: boolean;
            selected: ("KEY_RECALL" | "PRINCIPLE" | "DISTINGUISH" | "CONDITION" | "APPLY_CASE" | "CORRECT_MISCONCEPTION" | "EXPLAIN_OWN_WORDS")[];
        };
        PasteRequest: {
            text: string;
        };
        PlannedQuestion: {
            /** @enum {string} */
            goal: "KEY_RECALL" | "PRINCIPLE" | "DISTINGUISH" | "CONDITION" | "APPLY_CASE" | "CORRECT_MISCONCEPTION" | "EXPLAIN_OWN_WORDS";
            /** Format: int64 */
            memoryItemId: number;
            /** Format: int64 */
            relatedItemId: number | null;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "SHORT_ANSWER" | "ESSAY" | "ERROR_FINDING" | "CASE_JUDGMENT" | "CASE_APPLICATION";
        };
        PracticeView: {
            completed: boolean;
            /** @enum {string} */
            kind: "FIRST_STUDY" | "DAILY";
            /** Format: int64 */
            learningSessionId: number | null;
            /** Format: int64 */
            practiceId: number;
            /** Format: int32 */
            total: number;
        };
        Prerequisite: {
            concept: string;
            reason: string;
        };
        PresentationView: {
            choices: string[];
            /** Format: int32 */
            position: number;
            /** Format: int64 */
            presentationId: number;
            /** Format: int64 */
            questionId: number;
            sameDayRecheck: boolean;
            stem: string;
            /** Format: int32 */
            total: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "SHORT_ANSWER" | "ESSAY" | "ERROR_FINDING" | "CASE_JUDGMENT" | "CASE_APPLICATION";
        };
        QuestionView: {
            choices: string[];
            learningGoal: string;
            /** Format: int64 */
            memoryItemId: number;
            /** Format: int32 */
            position: number;
            /** Format: int64 */
            questionId: number;
            stem: string;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "SHORT_ANSWER" | "ESSAY" | "ERROR_FINDING" | "CASE_JUDGMENT" | "CASE_APPLICATION";
        };
        ReviewUnitResponse: {
            confusionPoints: components["schemas"]["ConfusionPointResponse"][];
            evidenceTurns: number[];
            keyPoints: components["schemas"]["KeyPointResponse"][];
            title: string;
        };
        SessionGauge: {
            /** Format: int64 */
            sessionId: number;
            units: components["schemas"]["UnitView"][];
        };
        ShareLinkRequest: {
            url: string;
        };
        StrengthRequest: {
            /** @enum {string} */
            strength: "LIGHT" | "UNDERSTAND" | "APPLY" | "MASTER";
        };
        Submission: {
            answer: string | null;
            /** Format: int32 */
            choiceIndex: number | null;
            /** Format: int64 */
            firstInputMs: number | null;
            /** Format: int64 */
            responseTimeMs: number | null;
            /** @enum {string|null} */
            selfAssessment: "RECALLED_EASILY" | "RECALLED_WITH_EFFORT" | "GUESSED" | null;
        };
        Summary: {
            completed: boolean;
            /** Format: date-time */
            completedAt: string | null;
            confirmed: components["schemas"]["SummaryItem"][];
            needsHelp: components["schemas"]["SummaryItem"][];
            /** Format: date-time */
            nextReviewAt: string | null;
            notChecked: components["schemas"]["SummaryItem"][];
            /** Format: int64 */
            sessionId: number;
            units: components["schemas"]["UnitView"][];
        };
        SummaryItem: {
            content: string;
            gauge: components["schemas"]["ItemGauge"];
            /** @enum {string} */
            kind: "FACT" | "WARNING" | "PRACTICE" | "CONFUSION";
            /** Format: int64 */
            memoryItemId: number;
            /** Format: date-time */
            nextReviewAt: string | null;
            /** Format: int64 */
            unitId: number;
            unitTitle: string;
        };
        Turn: {
            /** @enum {string|null} */
            aiVerdict: "confirmed" | "partial" | "corrected" | "not_applicable" | null;
            correction: string | null;
            /** Format: int32 */
            index: number;
            /** @enum {string} */
            intent: "info_request" | "rephrase_request" | "understanding_check" | "restatement" | "challenge" | "meta";
            quotedText: string | null;
            text: string;
        };
        TurnRequest: {
            /** @enum {string|null} */
            aiVerdict: "confirmed" | "partial" | "corrected" | "not_applicable" | null;
            correction: string | null;
            /** @enum {string} */
            intent: "info_request" | "rephrase_request" | "understanding_check" | "restatement" | "challenge" | "meta";
            text: string;
        };
        Unit: {
            evidenceTurns: number[];
            excluded: boolean;
            /** Format: int64 */
            id: number;
            items: components["schemas"]["Item"][];
            title: string;
            /** @enum {string} */
            verdict: "PENDING" | "APPROVED" | "HELD" | "REJECTED" | "UNAVAILABLE";
            verdictReason: string | null;
        };
        UnitGauge: {
            /** Format: double */
            average: number | null;
            /** Format: int32 */
            averagePercent: number | null;
            /** Format: int32 */
            checkedItems: number;
            /** Format: int32 */
            totalItems: number;
            /** Format: int64 */
            weakestItemId: number | null;
            /** Format: int32 */
            weakestPercent: number | null;
        };
        UnitView: {
            gauge: components["schemas"]["UnitGauge"];
            items: components["schemas"]["ItemView"][];
            title: string;
            /** Format: int64 */
            unitId: number;
        };
        UserTurnResponse: {
            /** @enum {string} */
            aiVerdict: "confirmed" | "partial" | "corrected" | "not_applicable";
            correction: string | null;
            /** Format: int32 */
            index: number;
            /** @enum {string} */
            intent: "info_request" | "rephrase_request" | "understanding_check" | "restatement" | "challenge" | "meta";
            quotedText: string | null;
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryResponse"][];
                };
            };
        };
    };
    paste: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeResponse"];
                };
            };
        };
    };
    shareLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareLinkRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
        };
    };
    today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyView"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyView"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionSummary"][];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDetail"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDetail"];
                };
            };
        };
    };
    item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExclusionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDetail"];
                };
            };
        };
    };
    insertTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTurnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDetail"];
                };
            };
        };
    };
    editTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
                index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDetail"];
                };
            };
        };
    };
    unit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
                unitId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExclusionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDetail"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsView"];
                };
            };
        };
    };
    readAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordAid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AidRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AidView"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Submission"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptView"];
                };
            };
        };
    };
    current: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackView"];
                };
            };
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackView"];
                };
            };
        };
    };
    next: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practiceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Next"];
                };
            };
        };
    };
    firstStudy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirstStudy"];
                };
            };
        };
    };
    startFirstStudy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeView"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
        };
    };
    options_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsView"];
                };
            };
        };
    };
    choose_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Composition"];
                };
            };
        };
    };
    gauge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionGauge"];
                };
            };
        };
    };
    options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Options"];
                };
            };
        };
    };
    choose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrengthRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
