/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConfusionPointResponse: {
            /** Format: int32 */
            turn: number;
            userBelief: string;
        };
        ConversationDetailResponse: {
            /** @enum {string} */
            fidelity: "verbatim" | "model_transcribed";
            id: string;
            /** @enum {string} */
            inputPath: "connector" | "share_link" | "paste";
            /** Format: date-time */
            receivedAt: string;
            reviewUnits: components["schemas"]["ReviewUnitResponse"][];
            topicHint: string | null;
            userTurns: components["schemas"]["UserTurnResponse"][];
            warnings: string[];
        };
        ConversationSummaryResponse: {
            /** @enum {string} */
            fidelity: "verbatim" | "model_transcribed";
            id: string;
            /** @enum {string} */
            inputPath: "connector" | "share_link" | "paste";
            /** Format: date-time */
            receivedAt: string;
            /** Format: int32 */
            reviewUnitCount: number;
            topicHint: string | null;
            /** Format: int32 */
            userTurnCount: number;
            /** Format: int32 */
            warningCount: number;
        };
        KeyPointResponse: {
            /** @enum {string} */
            kind: "fact" | "warning" | "practice";
            point: string;
            turns: number[];
        };
        ReviewUnitResponse: {
            confusionPoints: components["schemas"]["ConfusionPointResponse"][];
            evidenceTurns: number[];
            keyPoints: components["schemas"]["KeyPointResponse"][];
            title: string;
        };
        UserTurnResponse: {
            /** @enum {string} */
            aiVerdict: "confirmed" | "partial" | "corrected" | "not_applicable";
            correction: string | null;
            /** Format: int32 */
            index: number;
            /** @enum {string} */
            intent: "info_request" | "rephrase_request" | "understanding_check" | "restatement" | "challenge" | "meta";
            quotedText: string | null;
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryResponse"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
        };
    };
}
